### ISSUE TITLE
master: PhysicalEntitySimulation::prepareEntityForDelete(EntityItemPointer): Assertion `entity->isDead()' failed.

### ISSUE THREAD

**Issue by daleglass** [kasenvr/project-athena#337]
```interface: /home/dale/git/vircadia/vircadia-master/libraries/physics/src/PhysicalEntitySimulation.cpp:246: virtual void PhysicalEntitySimulation::prepareEntityForDelete(EntityItemPointer): Assertion `entity->isDead()' failed.```

I investigated this slightly. `PhysicalEntitySimulation::prepareEntityForDelete` checks if `entity->isDead()` is true. This seems sensible. The entity can be marked as dead by simply calling `entity->die()`, which simply sets an internal variable.

So I take this is simply a sanity check, and just adding a `die()` in the right place would fix things.

The likely culprit seems to be `OtherAvatar::removeOrb`. It was recently modified in commit ca8d64bc05c which is likely to be the problem.

```
(gdb) bt
#0  0x00007fffe6cc4625 in raise () from /lib64/libc.so.6
#1  0x00007fffe6cad8d9 in abort () from /lib64/libc.so.6
#2  0x00007fffe6cad7a9 in __assert_fail_base.cold () from /lib64/libc.so.6
#3  0x00007fffe6cbca66 in __assert_fail () from /lib64/libc.so.6
#4  0x00007ffff6d6b025 in PhysicalEntitySimulation::prepareEntityForDelete (this=0x1322990, entity=warning: RTTI symbol not found for class 'std::_Sp_counted_deleter<ShapeEntityItem*, ShapeEntityItem::baseFactory(EntityItemID const&, EntityItemProperties const&)::{lambda(EntityItem*)#1}, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'
warning: RTTI symbol not found for class 'std::_Sp_counted_deleter<ShapeEntityItem*, ShapeEntityItem::baseFactory(EntityItemID const&, EntityItemProperties const&)::{lambda(EntityItem*)#1}, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'
std::shared_ptr<EntityItem> (use count 15, weak count 1) = {...})
    at /home/dale/git/vircadia/vircadia-master/libraries/physics/src/PhysicalEntitySimulation.cpp:246
#5  0x00007ffff4ecffde in EntityTree::processRemovedEntities (this=0x16ab4920, theOperator=...)
    at /home/dale/git/vircadia/vircadia-master/libraries/entities/src/EntityTree.cpp:787
#6  0x00007ffff4ecfc28 in EntityTree::deleteEntitiesByPointer (this=0x16ab4920, entities=std::vector of length 1, capacity 1 = {...})
    at /home/dale/git/vircadia/vircadia-master/libraries/entities/src/EntityTree.cpp:753
#7  0x00007ffff4ea6fbc in EntityScriptingInterface::<lambda()>::operator()(void) const (__closure=0x7fffffff8350)
    at /home/dale/git/vircadia/vircadia-master/libraries/entities/src/EntityScriptingInterface.cpp:997
#8  0x00007ffff4eb3ed0 in ReadWriteLockable::withWriteLock<EntityScriptingInterface::deleteEntity(const QUuid&)::<lambda()> >(EntityScriptingInterface::<lambda()> &&) const
    (this=0x16ab4940, f=...) at /home/dale/git/vircadia/vircadia-master/libraries/shared/src/shared/ReadWriteLockable.h:64
#9  0x00007ffff4ea7136 in EntityScriptingInterface::deleteEntity (this=0x3ba0830, id=...)
    at /home/dale/git/vircadia/vircadia-master/libraries/entities/src/EntityScriptingInterface.cpp:977
#10 0x0000000000c4ae06 in OtherAvatar::removeOrb (this=0x1a58c900) at /home/dale/git/vircadia/vircadia-master/interface/src/avatar/OtherAvatar.cpp:59
#11 0x0000000000b920b6 in AvatarManager::updateOtherAvatars (this=0x3c0eb10, deltaTime=0.0165917613)
    at /home/dale/git/vircadia/vircadia-master/interface/src/avatar/AvatarManager.cpp:315
#12 0x00000000009ee9cb in Application::update (this=0x7fffffffaf30, deltaTime=0.0165917613) at /home/dale/git/vircadia/vircadia-master/interface/src/Application.cpp:6567
#13 0x00000000009e39b7 in Application::idle (this=0x7fffffffaf30) at /home/dale/git/vircadia/vircadia-master/interface/src/Application.cpp:5271
#14 0x00000000009df0da in Application::event (this=0x7fffffffaf30, event=0x7fff0deb89b0) at /home/dale/git/vircadia/vircadia-master/interface/src/Application.cpp:4212
#15 0x00007ffff45042a2 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /home/dale/git/vircadia/qt5-install/lib/libQt5Widgets.so.5
#16 0x00007ffff450d330 in QApplication::notify(QObject*, QEvent*) () from /home/dale/git/vircadia/qt5-install/lib/libQt5Widgets.so.5
#17 0x00000000009deed0 in Application::notify (this=0x7fffffffaf30, object=0x7fffffffaf30, event=0x7fff0deb89b0)
    at /home/dale/git/vircadia/vircadia-master/interface/src/Application.cpp:4182
#18 0x00007fffe7425d22 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /home/dale/git/vircadia/qt5-install/lib/libQt5Core.so.5
#19 0x00007fffe7428778 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /home/dale/git/vircadia/qt5-install/lib/libQt5Core.so.5
#20 0x00007fffe7479873 in ?? () from /home/dale/git/vircadia/qt5-install/lib/libQt5Core.so.5
#21 0x00007fffe68dc570 in g_main_context_dispatch () from /lib64/libglib-2.0.so.0
#22 0x00007fffe68dc900 in g_main_context_iterate.isra () from /lib64/libglib-2.0.so.0
#23 0x00007fffe68dc9a3 in g_main_context_iteration () from /lib64/libglib-2.0.so.0
#24 0x00007fffe7478f11 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /home/dale/git/vircadia/qt5-install/lib/libQt5Core.so.5
#25 0x00007fffe7424b0b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /home/dale/git/vircadia/qt5-install/lib/libQt5Core.so.5
#26 0x00007fffe742c11e in QCoreApplication::exec() () from /home/dale/git/vircadia/qt5-install/lib/libQt5Core.so.5
#27 0x0000000000cad11e in main (argc=1, argv=0x7fffffffe4c8) at /home/dale/git/vircadia/vircadia-master/interface/src/main.cpp:444
(gdb) frame 4
#4  0x00007ffff6d6b025 in PhysicalEntitySimulation::prepareEntityForDelete (this=0x1322990, entity=warning: RTTI symbol not found for class 'std::_Sp_counted_deleter<ShapeEntityItem*, ShapeEntityItem::baseFactory(EntityItemID const&, EntityItemProperties const&)::{lambda(EntityItem*)#1}, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'
warning: RTTI symbol not found for class 'std::_Sp_counted_deleter<ShapeEntityItem*, ShapeEntityItem::baseFactory(EntityItemID const&, EntityItemProperties const&)::{lambda(EntityItem*)#1}, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'
std::shared_ptr<EntityItem> (use count 15, weak count 1) = {...})

**Comment by daleglass** [comment]
I attempted to patch this, but more issues crop up elsewhere.

```
interface: /home/dale/git/vircadia/vircadia-master/libraries/physics/src/PhysicalEntitySimulation.cpp:246: virtual void PhysicalEntitySimulation::prepareEntityForDelete(EntityItemPointer): Assertion `entity->isDead()' failed.

Thread 76 "js:Entities 1" received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffdf896b700 (LWP 408792)]
0x00007fffe6c3b625 in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: dnf debuginfo-install lcms2-2.9-6.fc31.x86_64 libasyncns-0.8-17.fc31.x86_64 libmng-2.0.3-10.fc31.x86_64 libpng-1.6.37-2.fc31.x86_64 libsndfile-1.0.28-11.fc31.x86_64 libuuid-2.34-4.fc31.x86_64 nss-mdns-0.14.1-7.fc31.x86_64 pcre-8.44-1.fc31.x86_64 systemd-libs-243.8-1.fc31.x86_64 xcb-util-0.4.0-13.fc31.x86_64 xcb-util-image-0.4.0-13.fc31.x86_64
(gdb) bt
#0  0x00007fffe6c3b625 in raise () from /lib64/libc.so.6
#1  0x00007fffe6c248d9 in abort () from /lib64/libc.so.6
#2  0x00007fffe6c247a9 in __assert_fail_base.cold () from /lib64/libc.so.6
#3  0x00007fffe6c33a66 in __assert_fail () from /lib64/libc.so.6
#4  0x00007ffff6d4e613 in PhysicalEntitySimulation::prepareEntityForDelete (this=0x1334ea0, entity=warning: RTTI symbol not found for class 'std::_Sp_counted_deleter<ImageEntityItem*, ImageEntityItem::factory(EntityItemID const&, EntityItemProperties const&)::{lambda(EntityItem*)#1}, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'
warning: RTTI symbol not found for class 'std::_Sp_counted_deleter<ImageEntityItem*, ImageEntityItem::factory(EntityItemID const&, EntityItemProperties const&)::{lambda(EntityItem*)#1}, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'
std::shared_ptr<EntityItem> (use count 6, weak count 3) = {...})
    at /home/dale/git/vircadia/vircadia-master/libraries/physics/src/PhysicalEntitySimulation.cpp:246
#5  0x00007ffff4e640b4 in EntityTree::processRemovedEntities (this=0x15411620, theOperator=...)
    at /home/dale/git/vircadia/vircadia-master/libraries/entities/src/EntityTree.cpp:787
#6  0x00007ffff4e63cfe in EntityTree::deleteEntitiesByPointer (this=0x15411620, entities=std::vector of length 1, capacity 1 = {...})
    at /home/dale/git/vircadia/vircadia-master/libraries/entities/src/EntityTree.cpp:753
#7  0x00007ffff4e3b077 in EntityScriptingInterface::<lambda()>::operator()(void) const (__closure=0x7ffdf8967e60)
    at /home/dale/git/vircadia/vircadia-master/libraries/entities/src/EntityScriptingInterface.cpp:1001
#8  0x00007ffff4e47fa6 in ReadWriteLockable::withWriteLock<EntityScriptingInterface::deleteEntity(const QUuid&, bool)::<lambda()> >(EntityScriptingInterface::<lambda()> &&) const (this=0x15411640, f=...) at /home/dale/git/vircadia/vircadia-master/libraries/shared/src/shared/ReadWriteLockable.h:64
#9  0x00007ffff4e3b20b in EntityScriptingInterface::deleteEntity (this=0x3b99250, id=..., kill=false)
    at /home/dale/git/vircadia/vircadia-master/libraries/entities/src/EntityScriptingInterface.cpp:977
#10 0x00007ffff4d47832 in EntityScriptingInterface::qt_static_metacall (_o=0x3b99250, _c=QMetaObject::InvokeMetaMethod, _id=45, _a=0x7ffdf8969480)
    at /home/dale/git/vircadia/build-master/libraries/entities/entities_autogen/UVLADIE3JM/moc_EntityScriptingInterface.cpp:812
#11 0x00007ffff4d4df62 in EntityScriptingInterface::qt_metacall (this=0x3b99250, _c=QMetaObject::InvokeMetaMethod, _id=45, _a=0x7ffdf8969480)
    at /home/dale/git/vircadia/build-master/libraries/entities/entities_autogen/UVLADIE3JM/moc_EntityScriptingInterface.cpp:2022
#12 0x00007ffff03aab32 in ?? () from /home/dale/git/vircadia/qt5-install/lib/libQt5Script.so.5
#13 0x00007ffff03ab573 in ?? () from /home/dale/git/vircadia/qt5-install/lib/libQt5Script.so.5
#14 0x00007ffff03ab842 in ?? () from /home/dale/git/vircadia/qt5-install/lib/libQt5Script.so.5
#15 0x00007ffff02b5e1e in ?? () from /home/dale/git/vircadia/qt5-install/lib/libQt5Script.so.5
#16 0x00007ffff02854d6 in ?? () from /home/dale/git/vircadia/qt5-install/lib/libQt5Script.so.5
#17 0x00007fff24373b7a in ?? ()
#18 0x0000000000000000 in ?? ()
```
