### ISSUE TITLE
Interface crash when loading avatar with wrong armature

### ISSUE THREAD

**Issue by JulianGro** [kasenvr/project-athena#494]
When trying to load an avatar that has a wrong or missing armature selected, the interface crashes almost every time.
This happens to me on Linux Mint 19.3 (Ubuntu 18.04) with the v2020.2.2-rc AppImage from Dale.
Even though an avatar should never have this issue, the interface should not crash and ideally provide a warning that the armature is missing or corrupted.
An example avatar is here: http://94.130.177.235/Effole28.fbx

**Comment by kasenvr** [comment]
Could you post your log up to the crash? :)

**Comment by JulianGro** [comment]
good point

**Comment by kasenvr** [comment]
I was not able to crash myself with Windows when loading this avatar. I got well past the last error that you posted in your log. We'll need someone with Linux to repro this issue.

> OS Name	Microsoft Windows 10 Pro
> Version	10.0.18363 Build 18363
> Processor	AMD Ryzen 7 2700X Eight-Core Processor, 3700 Mhz, 8 Core(s), 16 Logical Processor(s)

**Comment by daleglass** [comment]
You should be able to get the info with the `coredumpctl` tool.

**Comment by JulianGro** [comment]
Might be related to https://github.com/vircadia/vircadia/issues/893

**Comment by JulianGro** [comment]
Here is a backtrace on 2020.3.3:
```
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007fffe504b899 in __GI_abort () at abort.c:79
#2  0x00007fffe504b769 in __assert_fail_base (fmt=0x7fffd0152195 "%s%s%s:%u: %s%sZusicherung »%s« nicht erfüllt.\n%n", assertion=0x5555562b55d1 "!fuzzyZero()", file=0x5555562b5560 "/home/motofckr9k/Vircadia/vcpkg/d2eb2afd/buildtrees/bullet3/src/392524cc77-dc9ca24e83/src/LinearMath/btVector3.h", line=305, 
    function=0x5555562b58c0 <btVector3::normalize()::__PRETTY_FUNCTION__> "btVector3& btVector3::normalize()") at assert.c:92
#3  0x00007fffe505d006 in __GI___assert_fail (assertion=0x5555562b55d1 "!fuzzyZero()", file=0x5555562b5560 "/home/motofckr9k/Vircadia/vcpkg/d2eb2afd/buildtrees/bullet3/src/392524cc77-dc9ca24e83/src/LinearMath/btVector3.h", line=305, 
    function=0x5555562b58c0 <btVector3::normalize()::__PRETTY_FUNCTION__> "btVector3& btVector3::normalize()") at assert.c:101
#4  0x000055555614690f in btVector3::normalize (this=0x7fffffff8cc0) at /home/motofckr9k/Vircadia/vcpkg/d2eb2afd/buildtrees/bullet3/src/392524cc77-dc9ca24e83/src/LinearMath/btVector3.h:305
#5  0x00007ffff661edca in btSingleRayCallback::btSingleRayCallback (this=0x7fffffff8d60, rayFromWorld=..., rayToWorld=..., world=0x555575353510, resultCallback=Warnung: RTTI symbol not found for class 'MyCharacterController::initRayShotgun(btCollisionWorld const*)::MeOnlyResultCallback'
...) at /home/motofckr9k/Vircadia/vcpkg/d2eb2afd/buildtrees/bullet3/src/392524cc77-dc9ca24e83/src/BulletCollision/CollisionDispatch/btCollisionWorld.cpp:939
#6  0x00007ffff661a861 in btCollisionWorld::rayTest (this=0x555575353510, rayFromWorld=..., rayToWorld=..., resultCallback=Warnung: RTTI symbol not found for class 'MyCharacterController::initRayShotgun(btCollisionWorld const*)::MeOnlyResultCallback'
...) at /home/motofckr9k/Vircadia/vcpkg/d2eb2afd/buildtrees/bullet3/src/392524cc77-dc9ca24e83/src/BulletCollision/CollisionDispatch/btCollisionWorld.cpp:994
#7  0x0000555555d82386 in MyCharacterController::initRayShotgun (this=0x555562f3fd80, world=0x555575353510) at /home/motofckr9k/Vircadia/source/interface/src/avatar/MyCharacterController.cpp:320
#8  0x0000555555d8039e in MyCharacterController::addToWorld (this=0x555562f3fd80) at /home/motofckr9k/Vircadia/source/interface/src/avatar/MyCharacterController.cpp:42
#9  0x00007ffff654fbdd in CharacterController::preSimulation (this=0x555562f3fd80) at /home/motofckr9k/Vircadia/source/libraries/physics/src/CharacterController.cpp:1021
#10 0x0000555555afe334 in Application::update (this=0x7fffffffad70, deltaTime=0.0487903208) at /home/motofckr9k/Vircadia/source/interface/src/Application.cpp:6578
#11 0x0000555555af3552 in Application::idle (this=0x7fffffffad70) at /home/motofckr9k/Vircadia/source/interface/src/Application.cpp:5328
#12 0x0000555555aee8d5 in Application::event (this=0x7fffffffad70, event=0x555578764ac0) at /home/motofckr9k/Vircadia/source/interface/src/Application.cpp:4264
#13 0x00007fffea182c8c in QApplicationPrivate::notify_helper (this=this@entry=0x5555608bf400, receiver=receiver@entry=0x7fffffffad70, e=e@entry=0x555578764ac0) at /home/nissim/qt5/qtbase/src/widgets/kernel/qapplication.cpp:3736
#14 0x00007fffea18a1e0 in QApplication::notify (this=0x7fffffffad70, receiver=0x7fffffffad70, e=0x555578764ac0) at /home/nissim/qt5/qtbase/src/widgets/kernel/qapplication.cpp:3483
#15 0x0000555555aee6cf in Application::notify (this=0x7fffffffad70, object=0x7fffffffad70, event=0x555578764ac0) at /home/motofckr9k/Vircadia/source/interface/src/Application.cpp:4234
#16 0x00007fffe59f06d8 in QCoreApplication::notifyInternal2 (receiver=0x7fffffffad70, event=0x555578764ac0) at /home/nissim/qt5/qtbase/src/corelib/kernel/qcoreapplication.cpp:1060
#17 0x00007fffe59f08ae in QCoreApplication::sendEvent (receiver=<optimized out>, event=event@entry=0x555578764ac0) at /home/nissim/qt5/qtbase/src/corelib/kernel/qcoreapplication.cpp:1450
#18 0x00007fffe59f3277 in QCoreApplicationPrivate::sendPostedEvents (receiver=receiver@entry=0x0, event_type=event_type@entry=0, data=0x555560357010) at /home/nissim/qt5/qtbase/src/corelib/kernel/qcoreapplication.cpp:1799
#19 0x00007fffe59f3818 in QCoreApplication::sendPostedEvents (receiver=receiver@entry=0x0, event_type=event_type@entry=0) at /home/nissim/qt5/qtbase/src/corelib/kernel/qcoreapplication.cpp:1653
#20 0x00007fffe5a4e333 in postEventSourceDispatch (s=0x555560ac1b70) at /home/nissim/qt5/qtbase/src/corelib/kernel/qeventdispatcher_glib.cpp:276
#21 0x00007fffdaf97417 in g_main_context_dispatch () from /tmp/.mount_VircadUN7qRO/vircadia/interface/../../qt5-install/lib/../../usr/lib64/libglib-2.0.so.0
#22 0x00007fffdaf97650 in ?? () from /tmp/.mount_VircadUN7qRO/vircadia/interface/../../qt5-install/lib/../../usr/lib64/libglib-2.0.so.0
#23 0x00007fffdaf976dc in g_main_context_iteration () from /tmp/.mount_VircadUN7qRO/vircadia/interface/../../qt5-install/lib/../../usr/lib64/libglib-2.0.so.0
#24 0x00007fffe5a4d93f in QEventDispatcherGlib::processEvents (this=0x555560b01940, flags=...) at /home/nissim/qt5/qtbase/src/corelib/kernel/qeventdispatcher_glib.cpp:422
#25 0x00007fffe59ee9fa in QEventLoop::exec (this=this@entry=0x7fffffffaaf0, flags=..., flags@entry=...) at /home/nissim/qt5/qtbase/src/corelib/kernel/qeventloop.cpp:225
#26 0x00007fffe59f7b40 in QCoreApplication::exec () at /home/nissim/qt5/qtbase/src/corelib/kernel/qcoreapplication.cpp:1363
#27 0x0000555555e0a2c3 in main (argc=1, argv=0x7fffffffdb18) at /home/motofckr9k/Vircadia/source/interface/src/main.cpp:448
(gdb) 
```

**Comment by JulianGro** [comment]
Yes :rage:
