### ISSUE TITLE
Crash in bullet3 on Linux, btVector3& btVector3::normalize(): Assertion `!fuzzyZero()' failed.

### ISSUE THREAD

**Issue by daleglass** [kasenvr/project-athena#745]
This came from 7b7038f , from @kasenvr 's incomplete PR #668  , but the crash seems unrelated to the PR itself, so it may be worth looking into.

```
[09/22 00:43:54] [DEBUG] [hifi.interface.deadlock] DEADLOCK WATCHDOG WARNING: lastHeartbeatAge: 13281 elapsedMovingAverage: 2301 maxElapsed: 226219 PREVIOUS maxElapsedAverage: 2299 NEW maxElapsedAverage: 2301 ** NEW MAX ELAPSED AVERAGE ** samples: 4647
[09/22 00:43:55] [DEBUG] [hifi.scriptengine] stopTimer -- not in _timerFunctionMap QObject(0x0)
[09/22 00:43:55] [DEBUG] [hifi.interface.deadlock] DEADLOCK WATCHDOG WARNING: lastHeartbeatAge: 13818 elapsedMovingAverage: 2303 maxElapsed: 226219 PREVIOUS maxElapsedAverage: 2301 NEW maxElapsedAverage: 2303 ** NEW MAX ELAPSED AVERAGE ** samples: 4657
interface: /home/dale/git/vircadia/vcpkg/bd824a32/buildtrees/bullet3/src/392524cc77-dc9ca24e83/src/LinearMath/btVector3.h:305: btVector3& btVector3::normalize(): Assertion `!fuzzyZero()' failed.

Thread 1 "interface" received signal SIGABRT, Aborted.
0x00007fffe6c52625 in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: dnf debuginfo-install SDL2-2.0.12-1.fc31.x86_64 glib2-2.62.6-2.fc31.x86_64 libX11-1.6.12-1.fc31.x86_64 libX11-xcb-1.6.12-1.fc31.x86_64 mesa-libGLU-9.0.1-1.fc31.x86_64 nspr-4.26.0-1.fc31.x86_64 nss-3.55.0-1.fc31.x86_64 nss-mdns-0.14.1-9.fc31.x86_64 nss-softokn-3.55.0-1.fc31.x86_64 nss-softokn-freebl-3.55.0-1.fc31.x86_64 nss-util-3.55.0-1.fc31.x86_64 opensc-0.20.0-3.fc31.x86_64 p11-kit-0.23.21-2.fc31.x86_64 pcre2-utf16-10.35-4.fc31.x86_64 pcsc-lite-libs-1.8.26-1.fc31.x86_64 pulseaudio-libs-13.99.1-4.fc31.x86_64 pulseaudio-libs-glib2-13.99.1-4.fc31.x86_64
(gdb) bt
#0  0x00007fffe6c52625 in raise () from /lib64/libc.so.6
#1  0x00007fffe6c3b8d9 in abort () from /lib64/libc.so.6
#2  0x00007fffe6c3b7a9 in __assert_fail_base.cold () from /lib64/libc.so.6
#3  0x00007fffe6c4aa66 in __assert_fail () from /lib64/libc.so.6
#4  0x0000000000f93a48 in btVector3::normalize (this=0x7fffffff5420)
    at /home/dale/git/vircadia/vcpkg/bd824a32/buildtrees/bullet3/src/392524cc77-dc9ca24e83/src/LinearMath/btVector3.h:305
#5  0x0000000000f93d96 in btVector3::normalized (this=0x7fffffff5560)
    at /home/dale/git/vircadia/vcpkg/bd824a32/buildtrees/bullet3/src/392524cc77-dc9ca24e83/src/LinearMath/btVector3.h:953
#6  0x00007ffff6d4995c in btGjkEpaPenetrationDepthSolver::calcPenDepth (this=0x16995280, simplexSolver=..., pConvexA=0x1fe75df0, 
    pConvexB=0x1fe75df0, transformA=..., transformB=..., v=..., wWitnessOnA=..., wWitnessOnB=..., debugDraw=0x16985db0)
    at /home/dale/git/vircadia/vcpkg/bd824a32/buildtrees/bullet3/src/392524cc77-dc9ca24e83/src/BulletCollision/NarrowPhaseCollision/btGjkEpaPenetrationDepthSolver.cpp:34
#7  0x00007ffff6d4c482 in btGjkPairDetector::getClosestPointsNonVirtual (this=0x7fffffff5e00, input=..., output=..., debugDraw=0x16985db0)
    at /home/dale/git/vircadia/vcpkg/bd824a32/buildtrees/bullet3/src/392524cc77-dc9ca24e83/src/BulletCollision/NarrowPhaseCollision/btGjkPairDetec
tor.cpp:1027
#8  0x00007ffff6d4a10a in btGjkPairDetector::getClosestPoints (this=0x7fffffff5e00, input=..., output=..., debugDraw=0x16985db0, 
    swapResults=false)
    at /home/dale/git/vircadia/vcpkg/bd824a32/buildtrees/bullet3/src/392524cc77-dc9ca24e83/src/BulletCollision/NarrowPhaseCollision/btGjkPairDetector.cpp:80
#9  0x00007ffff6d6bc10 in btConvexConvexAlgorithm::processCollision (this=0x16ce5fd0, body0Wrap=0x7fffffff6540, body1Wrap=0x7fffffff6570, 
    dispatchInfo=..., resultOut=0x7fffffff8120)
    at /home/dale/git/vircadia/vcpkg/bd824a32/buildtrees/bullet3/src/392524cc77-dc9ca24e83/src/BulletCollision/CollisionDispatch/btConvexConvexAlgorithm.cpp:699
#10 0x00007ffff6d67cb7 in btCompoundCompoundLeafCallback::Process (this=0x7fffffff7ed0, leaf0=0x16f44620, leaf1=0x16f44620)
    at /home/dale/git/vircadia/vcpkg/bd824a32/buildtrees/bullet3/src/392524cc77-dc9ca24e83/src/BulletCollision/CollisionDispatch/btCompoundCompoundCollisionAlgorithm.cpp:201
#11 0x00007ffff6d66ab7 in MycollideTT (root0=0x1fb18710, root1=0x1fb18710, xform=..., callback=0x7fffffff7ed0, distanceThreshold=0)
    at /home/dale/git/vircadia/vcpkg/bd824a32/buildtrees/bullet3/src/392524cc77-dc9ca24e83/src/BulletCollision/CollisionDispatch/btCompoundCompoundCollisionAlgorithm.cpp:277
#12 0x00007ffff6d66f66 in btCompoundCompoundCollisionAlgorithm::processCollision (this=0x16ce5f10, body0Wrap=0x7fffffff80c0, 
    body1Wrap=0x7fffffff80f0, dispatchInfo=..., resultOut=0x7fffffff8120)
    at /home/dale/git/vircadia/vcpkg/bd824a32/buildtrees/bullet3/src/392524cc77-dc9ca24e83/src/BulletCollision/CollisionDispatch/btCompoundCompoundCollisionAlgorithm.cpp:345
#13 0x00007ffff6d1f1bd in btCollisionDispatcher::defaultNearCallback (collisionPair=..., dispatcher=..., dispatchInfo=...)
    at /home/dale/git/vircadia/vcpkg/bd824a32/buildtrees/bullet3/src/392524cc77-dc9ca24e83/src/BulletCollision/CollisionDispatch/btCollisionDispatcher.cpp:255
#14 0x00007ffff6d1fb71 in btCollisionPairCallback::processOverlap (this=0x7fffffff82e0, pair=...)
--Type <RET> for more, q to quit, c to continue without paging--
cher.cpp:211
#15 0x00007ffff6d1c642 in btHashedOverlappingPairCache::processAllOverlappingPairs (this=0x152328f0, callback=0x7fffffff82e0, dispatcher=0x16da5560)
    at /home/dale/git/vircadia/vcpkg/bd824a32/buildtrees/bullet3/src/392524cc77-dc9ca24e83/src/BulletCollision/BroadphaseCollision/btOverlappingPairCache.cpp:341
#16 0x00007ffff6d1c928 in btHashedOverlappingPairCache::processAllOverlappingPairs (this=0x152328f0, callback=0x7fffffff82e0, dispatcher=0x16da5560, dispatchInfo=...)
    at /home/dale/git/vircadia/vcpkg/bd824a32/buildtrees/bullet3/src/392524cc77-dc9ca24e83/src/BulletCollision/BroadphaseCollision/btOverlappingPairCache.cpp:412
#17 0x00007ffff6d1ef89 in btCollisionDispatcher::dispatchAllCollisionPairs (this=0x16da5560, pairCache=0x152328f0, dispatchInfo=..., dispatcher=0x16da5560)
    at /home/dale/git/vircadia/vcpkg/bd824a32/buildtrees/bullet3/src/392524cc77-dc9ca24e83/src/BulletCollision/CollisionDispatch/btCollisionDispatcher.cpp:224
#18 0x00007ffff6d21061 in btCollisionWorld::performDiscreteCollisionDetection (this=0x16daa700) at /home/dale/git/vircadia/vcpkg/bd824a32/buildtrees/bullet3/src/392524cc77-dc9ca24e83/src/BulletCollision/CollisionDispatch/btCollisionWorld.cpp:234
#19 0x00007ffff6d064ce in btDiscreteDynamicsWorld::internalSingleStepSimulation (this=0x16daa700, timeStep=0.0111111114) at /home/dale/git/vircadia/vcpkg/bd824a32/buildtrees/bullet3/src/392524cc77-dc9ca24e83/src/BulletDynamics/Dynamics/btDiscreteDynamicsWorld.cpp:473
#20 0x00007ffff6ce7505 in ThreadSafeDynamicsWorld::stepSimulationWithSubstepCallback(float, int, float, std::function<void ()>) (this=0x16daa700, timeStep=0.0139349997, maxSubSteps=6, fixedTimeStep=0.0111111114, onSubStep=...)
    at /home/dale/git/vircadia/vircadia-master/libraries/physics/src/ThreadSafeDynamicsWorld.cpp:78
#21 0x00007ffff6ccdaf3 in PhysicsEngine::stepSimulation (this=0x3b94490) at /home/dale/git/vircadia/vircadia-master/libraries/physics/src/PhysicsEngine.cpp:323
#22 0x00000000009f2413 in Application::<lambda()>::operator()(void) const (__closure=0x7fffffff9180) at /home/dale/git/vircadia/vircadia-master/interface/src/Application.cpp:6543
#23 0x0000000000a15106 in ReadWriteLockable::withWriteLock<Application::update(float)::<lambda()> >(Application::<lambda()> &&) const (this=0x1530c260, f=...) at /home/dale/git/vircadia/vircadia-master/libraries/shared/src/shared/ReadWriteLockable.h:64

#24 0x00000000009f46b1 in Application::update (this=0x7fffffffabf0, deltaTime=0.0159465466) at /home/dale/git/vircadia/vircadia-master/interface/src/Application.cpp:6542
#25 0x00000000009e9b25 in Application::idle (this=0x7fffffffabf0) at /home/dale/git/vircadia/vircadia-master/interface/src/Application.cpp:5303
#26 0x00000000009e5248 in Application::event (this=0x7fffffffabf0, event=0x7ffef02eb8e0) at /home/dale/git/vircadia/vircadia-master/interface/src/Application.cpp:4244
#27 0x00007ffff43b22a2 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /home/dale/git/vircadia/qt5-install/lib/libQt5Widgets.so.5
#28 0x00007ffff43bb330 in QApplication::notify(QObject*, QEvent*) () from /home/dale/git/vircadia/qt5-install/lib/libQt5Widgets.so.5
#29 0x00000000009e503e in Application::notify (this=0x7fffffffabf0, object=0x7fffffffabf0, event=0x7ffef02eb8e0) at /home/dale/git/vircadia/vircadia-master/interface/src/Application.cpp:4214
#30 0x00007fffe73b3d22 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /home/dale/git/vircadia/qt5-install/lib/libQt5Core.so.5
#31 0x00007fffe73b6778 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /home/dale/git/vircadia/qt5-install/lib/libQt5Core.so.5
#32 0x00007fffe7407873 in ?? () from /home/dale/git/vircadia/qt5-install/lib/libQt5Core.so.5
#33 0x00007fffe6868570 in g_main_context_dispatch () from /lib64/libglib-2.0.so.0
#34 0x00007fffe6868900 in g_main_context_iterate.isra () from /lib64/libglib-2.0.so.0
#35 0x00007fffe68689a3 in g_main_context_iteration () from /lib64/libglib-2.0.so.0
#36 0x00007fffe7406f11 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /home/dale/git/vircadia/qt5-install/lib/libQt5Core.so.5
#37 0x00007fffe73b2b0b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /home/dale/git/vircadia/qt5-install/lib/libQt5Core.so.5
#38 0x00007fffe73ba11e in QCoreApplication::exec() () from /home/dale/git/vircadia/qt5-install/lib/libQt5Core.so.5
#39 0x0000000000ccbcd3 in main (argc=1, argv=0x7fffffffe1a8) at /home/dale/git/vircadia/vircadia-master/interface/src/main.cpp:445
```

**Comment by daleglass** [comment]
I'm not sure whether this one still happens. I don't seem to have run into it again.

**Comment by JulianGro** [comment]
We just saw this one happen. Shocktail picked up a bodypillow and we all crashed (all Linux users)
```
Vircadia-x86_64_v2021.1.2-Eos.AppImage: /home/motofckr9k/Vircadia/vcpkg/92834ad7/buildtrees/bullet3/src/392524cc77-dc9ca24e83/src/LinearMath/btVector3.h:305: btVector3& btVector3::normalize(): Assertion `!fuzzyZero()' failed.
```
